/*
 * File: app/view/ChannelStats_Panel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ChannelStats_Panel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ChannelStats_Panel',

    requires: [
        'Ext.tab.Panel',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column',
        'Ext.tab.Tab'
    ],

    height: 250,
    itemId: 'ChannelStats_Panel',
    margin: '0 0 0 3',
    width: 400,

    layout: {
        type: 'hbox',
        align: 'stretch',
        defaultMargins: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0
        }
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Stats',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    itemId: 'ChannelStats_Chart_Panel'
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    itemId: 'ChannelStats_Grid_Panel',
                                    forceFit: true,
                                    store: 'ChannelStats',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'channel',
                                            text: 'Channel'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'last',
                                            text: 'Last'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'average',
                                            text: 'Avg'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'std',
                                            text: 'Std'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'max',
                                            text: 'Max'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'min',
                                            text: 'Min'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            layout: 'fit',
                            title: 'Histogram',
                            items: [
                                {
                                    xtype: 'panel',
                                    itemId: 'ChannelStats_Histogram_Panel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});