/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'MyApp.view.Spike_Candle_Panel',
        'MyApp.view.Spike_Channel_Panel',
        'MyApp.view.SpikeRevised_Candle_Panel',
        'MyApp.view.SpikeRevised_Channel_Panel',
        'MyApp.view.ChannelStats_Panel',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.form.FieldContainer',
        'Ext.form.Label',
        'Ext.form.field.Date',
        'Ext.form.field.Time'
    ],

    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    region: 'north',
                    height: 52,
                    layout: 'fit'
                },
                {
                    xtype: 'container',
                    region: 'west',
                    itemId: 'Controls',
                    width: 150,
                    layout: 'accordion',
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'SpikeControls',
                            layout: 'fit',
                            title: 'Spike',
                            dockedItems: [
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        MyApp.app.getController("Spike").showCandle();
                                    },
                                    dock: 'top',
                                    margin: '5 0 0 0',
                                    text: 'Candle Chart'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        MyApp.app.getController("Spike").showChannel();
                                    },
                                    dock: 'top',
                                    disabled: true,
                                    itemId: 'Chart2Button',
                                    margin: '5 0 0 0',
                                    allowDepress: false,
                                    text: 'Channel Chart'
                                },
                                {
                                    xtype: 'button',
                                    dock: 'top',
                                    itemId: 'SpikeChoiceSeries',
                                    margin: '20 0 0 0',
                                    text: 'Choice a Series',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                handler: function(item, e) {
                                                    MyApp.app.getController("Spike").changeSeries(0);
                                                },
                                                text: 'Incorrected'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                handler: function(item, e) {
                                                    MyApp.app.getController("Spike").changeSeries(1);
                                                },
                                                text: 'Corrected for Pressure'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                handler: function(item, e) {
                                                    MyApp.app.getController("Spike").changeSeries(2);
                                                },
                                                text: 'Corrected for Efficiency'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    dock: 'top',
                                    itemId: 'SpikeIntervalSearch',
                                    margin: '20 0 0 0',
                                    width: 200,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            text: 'From: '
                                        },
                                        {
                                            xtype: 'datefield',
                                            itemId: 'SpikeIntervalDateFrom',
                                            fieldLabel: 'From',
                                            hideLabel: true,
                                            labelWidth: 50,
                                            size: 18,
                                            format: 'Y-m-d'
                                        },
                                        {
                                            xtype: 'timefield',
                                            itemId: 'SpikeIntervalHourFrom',
                                            labelWidth: 0,
                                            size: 18,
                                            format: 'H:i:s'
                                        },
                                        {
                                            xtype: 'label',
                                            text: 'To:'
                                        },
                                        {
                                            xtype: 'datefield',
                                            itemId: 'SpikeIntervalDateTo',
                                            fieldLabel: 'To',
                                            hideLabel: true,
                                            labelWidth: 50,
                                            size: 18,
                                            format: 'Y-m-d'
                                        },
                                        {
                                            xtype: 'timefield',
                                            itemId: 'SpikeIntervalHourTo',
                                            size: 18,
                                            format: 'H:i:s'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                start=Ext.ComponentQuery.query('#Controls')[0].down('#SpikeControls').down('#SpikeIntervalSearch').down('#SpikeIntervalDateFrom').getRawValue()+' '+Ext.ComponentQuery.query('#Controls')[0].down('#SpikeControls').down('#SpikeIntervalSearch').down('#SpikeIntervalHourFrom').getRawValue();
                                                finish=Ext.ComponentQuery.query('#Controls')[0].down('#SpikeControls').down('#SpikeIntervalSearch').down('#SpikeIntervalDateTo').getRawValue()+' '+Ext.ComponentQuery.query('#Controls')[0].down('#SpikeControls').down('#SpikeIntervalSearch').down('#SpikeIntervalHourTo').getRawValue();
                                                MyApp.app.getController("Spike").searchInterval(start, finish);
                                            },
                                            margin: '5 0 0 0',
                                            text: 'Search'
                                        }
                                    ]
                                }
                            ],
                            listeners: {
                                beforeexpand: {
                                    fn: me.onPanelBeforeExpand1,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'panel',
                            itemId: 'SpikeRevisedControls',
                            title: 'Spike Revised',
                            listeners: {
                                beforeexpand: {
                                    fn: me.onPanelBeforeExpand,
                                    scope: me
                                }
                            },
                            dockedItems: [
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        MyApp.app.getController("SpikeRevised").showCandle();
                                    },
                                    dock: 'top',
                                    margin: '5 0 0 0',
                                    text: 'Candle Chart'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        MyApp.app.getController("SpikeRevised").showChannel();
                                    },
                                    dock: 'top',
                                    disabled: true,
                                    itemId: 'SpikeRevisedChannelChart',
                                    margin: '5 0 0 0',
                                    allowDepress: false,
                                    text: 'Channel Chart'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        MyApp.app.getController("SpikeRevised").showHideGrid();
                                    },
                                    dock: 'top',
                                    itemId: 'SpikeRevisedShowGrid',
                                    margin: '15 0 0 0',
                                    text: 'Selected Points'
                                },
                                {
                                    xtype: 'button',
                                    dock: 'top',
                                    itemId: 'SpikeRevisedChoiceSeries',
                                    margin: '15 0 0 0',
                                    text: 'Choice a Series',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                handler: function(item, e) {
                                                    MyApp.app.getController("SpikeRevised").changeSeries(0);
                                                },
                                                text: 'Incorrected'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                handler: function(item, e) {
                                                    MyApp.app.getController("SpikeRevised").changeSeries(1);
                                                },
                                                text: 'Corrected for Pressure'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                handler: function(item, e) {
                                                    MyApp.app.getController("SpikeRevised").changeSeries(2);
                                                },
                                                text: 'Corrected for Efficiency'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    dock: 'top',
                                    itemId: 'SpikeRevisedIntervalSearch',
                                    margin: '15 0 0 0',
                                    width: 200,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            text: 'From: '
                                        },
                                        {
                                            xtype: 'datefield',
                                            itemId: 'SpikeIntervalDateFrom',
                                            fieldLabel: 'From',
                                            hideLabel: true,
                                            labelWidth: 50,
                                            size: 18,
                                            format: 'Y-m-d'
                                        },
                                        {
                                            xtype: 'timefield',
                                            itemId: 'SpikeIntervalHourFrom',
                                            labelWidth: 0,
                                            size: 18,
                                            format: 'H:i:s'
                                        },
                                        {
                                            xtype: 'label',
                                            text: 'To:'
                                        },
                                        {
                                            xtype: 'datefield',
                                            itemId: 'SpikeIntervalDateTo',
                                            fieldLabel: 'To',
                                            hideLabel: true,
                                            labelWidth: 50,
                                            size: 18,
                                            format: 'Y-m-d'
                                        },
                                        {
                                            xtype: 'timefield',
                                            itemId: 'SpikeIntervalHourTo',
                                            size: 18,
                                            format: 'H:i:s'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                start=Ext.ComponentQuery.query('#Controls')[0].down('#SpikeRevisedControls').down('#SpikeRevisedIntervalSearch').down('#SpikeIntervalDateFrom').getRawValue()+' '+Ext.ComponentQuery.query('#Controls')[0].down('#SpikeRevisedControls').down('#SpikeRevisedIntervalSearch').down('#SpikeIntervalHourFrom').getRawValue();
                                                finish=Ext.ComponentQuery.query('#Controls')[0].down('#SpikeRevisedControls').down('#SpikeRevisedIntervalSearch').down('#SpikeIntervalDateTo').getRawValue()+' '+Ext.ComponentQuery.query('#Controls')[0].down('#SpikeRevisedControls').down('#SpikeRevisedIntervalSearch').down('#SpikeIntervalHourTo').getRawValue();
                                                MyApp.app.getController("SpikeRevised").searchInterval(start, finish);
                                            },
                                            margin: '5 0 0 0',
                                            text: 'Search'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'ChannelStatsControls',
                            title: 'ChannelStats',
                            listeners: {
                                beforeexpand: {
                                    fn: me.onPanelBeforeExpand2,
                                    scope: me
                                }
                            },
                            dockedItems: [
                                {
                                    xtype: 'fieldcontainer',
                                    dock: 'top',
                                    itemId: 'ChannelStatsIntervalSearch',
                                    margin: '20 0 0 0',
                                    width: 200,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            text: 'From: '
                                        },
                                        {
                                            xtype: 'datefield',
                                            itemId: 'IntervalDateFrom',
                                            fieldLabel: 'From',
                                            hideLabel: true,
                                            labelWidth: 50,
                                            size: 18,
                                            format: 'Y-m-d'
                                        },
                                        {
                                            xtype: 'timefield',
                                            itemId: 'IntervalHourFrom',
                                            labelWidth: 0,
                                            size: 18,
                                            format: 'H:i:s'
                                        },
                                        {
                                            xtype: 'label',
                                            text: 'To:'
                                        },
                                        {
                                            xtype: 'datefield',
                                            itemId: 'IntervalDateTo',
                                            fieldLabel: 'To',
                                            hideLabel: true,
                                            labelWidth: 50,
                                            size: 18,
                                            format: 'Y-m-d'
                                        },
                                        {
                                            xtype: 'timefield',
                                            itemId: 'IntervalHourTo',
                                            size: 18,
                                            format: 'H:i:s'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                start=Ext.ComponentQuery.query('#Controls')[0].down('#ChannelStatsControls').down('#ChannelStatsIntervalSearch').down('#IntervalDateFrom').getRawValue()+' '+Ext.ComponentQuery.query('#Controls')[0].down('#ChannelStatsControls').down('#ChannelStatsIntervalSearch').down('#IntervalHourFrom').getRawValue();
                                                finish=Ext.ComponentQuery.query('#Controls')[0].down('#ChannelStatsControls').down('#ChannelStatsIntervalSearch').down('#IntervalDateTo').getRawValue()+' '+Ext.ComponentQuery.query('#Controls')[0].down('#ChannelStatsControls').down('#ChannelStatsIntervalSearch').down('#IntervalHourTo').getRawValue();
                                                MyApp.app.getController("ChannelStats").searchInterval(start, finish);

                                            },
                                            margin: '5 0 0 0',
                                            text: 'Search'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    region: 'center',
                    itemId: 'NavigationPanel',
                    layout: 'card',
                    items: [
                        {
                            xtype: 'Spike_Candle_Panel'
                        },
                        {
                            xtype: 'Spike_Channel_Panel'
                        },
                        {
                            xtype: 'SpikeRevised_Candle_Panel'
                        },
                        {
                            xtype: 'SpikeRevised_Channel_Panel'
                        },
                        {
                            xtype: 'ChannelStats_Panel'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onPanelBeforeExpand1: function(p, animate, eOpts) {
        Ext.History.add('Spike');
    },

    onPanelBeforeExpand: function(p, animate, eOpts) {
        Ext.History.add('SpikeRevised');
    },

    onPanelBeforeExpand2: function(p, animate, eOpts) {
        Ext.History.add('ChannelStats');
    }

});