/*
 * File: app/view/SpikeRevised_Candle_Panel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SpikeRevised_Candle_Panel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.SpikeRevised_Candle_Panel',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Date',
        'Ext.grid.column.Number',
        'Ext.grid.column.Action',
        'Ext.button.Button'
    ],

    height: 413,
    itemId: 'SpikeRevised_Candle_Panel',
    margin: '0 0 0 3',
    width: 729,

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 3,
                    itemId: 'SpikeRevised_Candle_Chart_Panel'
                },
                {
                    xtype: 'panel',
                    flex: 3,
                    floating: true,
                    height: 400,
                    itemId: 'SpikeRevised_Candle_Grid_Panel',
                    width: 400,
                    title: 'Marked Data',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 2,
                            itemId: 'GridPanel',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    itemId: 'SpikeRevised_MarkedGrid',
                                    forceFit: true,
                                    store: 'RevisitedData',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            minWidth: 50,
                                            dataIndex: 'label',
                                            text: 'Label'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            minWidth: 140,
                                            dataIndex: 'start_date_time',
                                            text: 'Start_date_time',
                                            format: 'Y-m-d H:i:s'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            minWidth: 70,
                                            dataIndex: 'un',
                                            text: 'Un'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            minWidth: 70,
                                            dataIndex: 'ce',
                                            text: 'Ce'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            minWidth: 70,
                                            dataIndex: 'cp',
                                            text: 'Cp'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            minWidth: 70,
                                            dataIndex: 'pr',
                                            text: 'Pr'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            minWidth: 50,
                                            dataIndex: 'ver',
                                            text: 'Ver',
                                            format: '0,000'
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            minWidth: 50,
                                            items: [
                                                {
                                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                        MyApp.app.getController("SpikeRevised").removeFromGrid(rowIndex);


                                                    },
                                                    icon: 'resources/icons/trash.png'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'panel',
                            dock: 'bottom',
                            itemId: 'ButtonPanel',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        MyApp.app.getController("SpikeRevised").submitGrid();
                                    },
                                    flex: 1,
                                    margin: '5 0 5 5',
                                    text: 'Submit'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        MyApp.app.getController("SpikeRevised").clearGrid();
                                    },
                                    flex: 1,
                                    margin: '5 0 5 5',
                                    text: 'Clear'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        MyApp.app.getController("SpikeRevised").showHideGrid();
                                    },
                                    flex: 1,
                                    margin: '5 5 5 5',
                                    text: 'Hide'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});