/*
 * File: app/controller/Navigation.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Navigation', {
    extend: 'Ext.app.Controller',

    requires: [
        'Ext.History'
    ],

    refs: [
        {
            ref: 'SpikeChartPanel',
            selector: '#SpikeChartPanel'
        },
        {
            ref: 'SpikeStatPanel',
            selector: '#SpikeStatPanel'
        },
        {
            ref: 'navigationPanel',
            selector: '#NavigationPanel'
        },
        {
            ref: 'SpikeCorrPanel',
            selector: '#SpikeCorrPanel'
        },
        {
            ref: 'SpikeChannelChartPanel',
            selector: '#SpikeChannelChartPanel'
        },
        {
            ref: 'ChannelStatsPanel',
            selector: '#ChannelStatsPanel'
        }
    ],

    onLaunch: function() {
        Ext.History.init();

        var onHistoryChange=function (hash){
            switch(hash){
                case 'Spike':
                    MyApp.app.getController("Spike").showCandle();
                    break;
                case 'SpikeRevised':
                    MyApp.app.getController("SpikeRevised").showCandle();
                    break;
                case 'ChannelStats':
                    MyApp.app.getController("ChannelStats").showModule();
                    break;

                default:
                    console.log(hash);
                    break;
            }
        };

        Ext.History.on('change', onHistoryChange, this);
        if(Ext.History.getToken() === null){
            Ext.History.add('Spike');}
        else{
            onHistoryChange(Ext.History.getToken());}
    }

});
